# ----------------------------------------
# Created on: Mon Sep 22 21:12:57 2025
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "PDS_SIM_LIB_PATH/usim"
vmap  adc "PDS_SIM_LIB_PATH/adc"
vmap  ddrc "PDS_SIM_LIB_PATH/ddrc"
vmap  ddrphy "PDS_SIM_LIB_PATH/ddrphy"
vmap  hsst_e2 "PDS_SIM_LIB_PATH/hsst_e2"
vmap  iolhr_dft "PDS_SIM_LIB_PATH/iolhr_dft"
vmap  ipal_e1 "PDS_SIM_LIB_PATH/ipal_e1"
vmap  pciegen2 "PDS_SIM_LIB_PATH/pciegen2"
vlog -f define.f -work work   \
"../RTL_code/other_item/signal_sync..v"\
"../Verification_model/axi_mem_test_model.v"\
"../Behave_simulation/sim_log/sgm/tb_sgm_new.v"\
"../RTL_code/algorithm_data_engine/sgm_data_engine.v"\
"../RTL_code/algorithm/rgb2gray.v"\
"../RTL_code/algorithm/double_camera_vision/census_5x5.v"\
"../RTL_code/algorithm/double_camera_vision/matrix_5x5.v"\
"../RTL_code/algorithm/double_camera_vision/sgm_new_2.v"\
"../ipcore/FIFO_8w1024d/rtl/ipml_reg_fifo_v1_1_FIFO_8w1024d.v"\
"../ipcore/FIFO_8w1024d/FIFO_8w1024d.v"\
"../ipcore/FIFO_8w1024d/FIFO_8w1024d_prefetch.v"\
"../ipcore/FIFO_8w1024d/rtl/ipml_fifo_ctrl_v1_4_FIFO_8w1024d.v"\
"../ipcore/FIFO_8w1024d/rtl/ipml_fifo_v1_9_FIFO_8w1024d.v"\
"../ipcore/FIFO_8w1024d/rtl/ipml_prefetch_fifo_v1_9_FIFO_8w1024d.v"\
"../ipcore/FIFO_8w1024d/rtl/ipml_sdpram_v1_9_FIFO_8w1024d.v"\
"../ipcore/sgm_data_fifo/sgm_data_fifo.v"\
"../ipcore/sgm_data_fifo/sgm_data_fifo_prefetch.v"\
"../ipcore/sgm_data_fifo/sgm_data_fifo_tb.v"\
"../ipcore/sgm_data_fifo/rtl/ipml_fifo_ctrl_v1_4_sgm_data_fifo.v"\
"../ipcore/sgm_data_fifo/rtl/ipml_fifo_v1_9_sgm_data_fifo.v"\
"../ipcore/sgm_data_fifo/rtl/ipml_prefetch_fifo_v1_9_sgm_data_fifo.v"\
"../ipcore/sgm_data_fifo/rtl/ipml_reg_fifo_v1_1_sgm_data_fifo.v"\
"../ipcore/sgm_data_fifo/rtl/ipml_sdpram_v1_9_sgm_data_fifo.v"\
"../ipcore/sgm_hamming_fifo/sgm_hamming_fifo.v"\
"../ipcore/sgm_hamming_fifo/sgm_hamming_fifo_prefetch.v"\
"../ipcore/sgm_hamming_fifo/rtl/ipml_fifo_ctrl_v1_4_sgm_hamming_fifo.v"\
"../ipcore/sgm_hamming_fifo/rtl/ipml_fifo_v1_9_sgm_hamming_fifo.v"\
"../ipcore/sgm_hamming_fifo/rtl/ipml_prefetch_fifo_v1_9_sgm_hamming_fifo.v"\
"../ipcore/sgm_hamming_fifo/rtl/ipml_reg_fifo_v1_1_sgm_hamming_fifo.v"\
"../ipcore/sgm_hamming_fifo/rtl/ipml_sdpram_v1_9_sgm_hamming_fifo.v"\
"../ipcore/sgm_lr2_ram/sgm_lr2_ram.v"\
"../ipcore/sgm_lr2_ram/rtl/ipml_dpram_v1_8_sgm_lr2_ram.v"\
"../ipcore/drm_fifo_256b_8d/drm_fifo_256b_8d.v"\
"../ipcore/drm_fifo_256b_8d/drm_fifo_256b_8d_prefetch.v"\
"../ipcore/drm_fifo_256b_8d/rtl/ipml_fifo_ctrl_v1_4_drm_fifo_256b_8d.v"\
"../ipcore/drm_fifo_256b_8d/rtl/ipml_fifo_v1_9_drm_fifo_256b_8d.v"\
"../ipcore/drm_fifo_256b_8d/rtl/ipml_prefetch_fifo_v1_9_drm_fifo_256b_8d.v"\
"../ipcore/drm_fifo_256b_8d/rtl/ipml_reg_fifo_v1_1_drm_fifo_256b_8d.v"\
"../ipcore/drm_fifo_256b_8d/rtl/ipml_sdpram_v1_9_drm_fifo_256b_8d.v"\
"../ipcore/smg_lr0_ram/sgm_lr0_ram.v"\
"../ipcore/smg_lr0_ram/rtl/ipml_dpram_v1_8_sgm_lr0_ram.v"\
"../ipcore/cmr_census_fifo/cmr_census_fifo.v"\
"../ipcore/cmr_census_fifo/cmr_census_fifo_prefetch.v"\
"../ipcore/cmr_census_fifo/rtl/ipml_fifo_ctrl_v1_4_cmr_census_fifo.v"\
"../ipcore/cmr_census_fifo/rtl/ipml_fifo_v1_9_cmr_census_fifo.v"\
"../ipcore/cmr_census_fifo/rtl/ipml_prefetch_fifo_v1_9_cmr_census_fifo.v"\
"../ipcore/cmr_census_fifo/rtl/ipml_reg_fifo_v1_1_cmr_census_fifo.v"\
"../ipcore/cmr_census_fifo/rtl/ipml_sdpram_v1_9_cmr_census_fifo.v"\
"../ipcore/sgm_vsync_fifo/sgm_vsync_fifo.v"\
"../ipcore/sgm_vsync_fifo/rtl/ipm_distributed_fifo_ctr_v1_1_sgm_vsync_fifo.v"\
"../ipcore/sgm_vsync_fifo/rtl/ipm_distributed_fifo_v1_4_sgm_vsync_fifo.v"\
"../ipcore/sgm_vsync_fifo/rtl/ipm_distributed_sdpram_v1_3_sgm_vsync_fifo.v"


