import os
import numpy as np


FPGA_PARAMS = {
    "CMR_1_DISP_AREA_H_OFST": 160,
    "CMR_1_DISP_AREA_V_OFST": 32,
    "CMR_2_DISP_AREA_H_OFST": 1120,
    "CMR_2_DISP_AREA_V_OFST": 32,
}

SGM_DISP_PARAMS = {
    "H_OFST": 160,
    "V_OFST": 562,
    "WIDTH": 640,
    "HEIGHT": 480,
    "SCALE_FACTOR": 1,
    "MAX_DISPARITY": 47,
    "INVALID_R_THRESH": 200,
    "INVALID_G_THRESH": 50,
    "INVALID_B_THRESH": 50,
    "SUBPIXEL_ENABLED": True,
    "SUBPIXEL_DIVISOR": 2.0,
}

PCD_PARAMS = {
    "REFRESH_RATE_HZ": 5,
    "VOXEL_SIZE_PX": 4,
    "POINT_SIZE": 3,
    "Z_MAX_CM": 500.0,
    "Z_MIN_CM": 30.0,
    "DOWNSAMPLE_ENABLED": True,
    "BG_COLOR": (0.08, 0.08, 0.12),
    "CAM_CX": 315,
    "CAM_CY": 229,
    "COLOR_BY_DEPTH": True,
    "MAX_POINTS": 50000,
}

CROP_WIDTH = 640
CROP_HEIGHT = 480

FRAME_WIDTH = 1920
FRAME_HEIGHT = 1080

MODEL_WEIGHTS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "weights",
    "yolov8n.pt",
)

PNP_MIN_CONTOUR_AREA_RATIO = 0.05
PNP_CONTOUR_APPROX_EPSILON = 0.02
PNP_ORB_NFEATURES = 2000
PNP_ORB_GOOD_MATCH_DIST = 50
PNP_SIMILARITY_THRESHOLD = 0.15
PNP_DIST_COEFFS = np.zeros((4, 1), dtype=np.float32)
PNP_PCB_OUTLINE_COLOR = (0, 255, 255)
PNP_DRAW_AXIS_LENGTH_RATIO = 0.3
PNP_DRAW_NORMAL_LENGTH_RATIO = 0.8
PNP_PYRAMID_SCALES = [0.3, 0.5, 0.75, 1.0, 1.5, 2.0]

PNP_GPU_MATCHING_ENABLED = True
PNP_MECHANICAL_MATCH_INTERVAL = 1
PNP_YOLO_TRIGGER_INTERVAL = 15
PNP_TARGET_LOST_FRAMES = 8
PNP_TARGET_MOVE_THRESHOLD_PX = 80

MODEL_CONF_THRESHOLD = 0.25
MODEL_IOU_THRESHOLD = 0.45
MODEL_INFERENCE_SKIP = 2

PCB_BOARD_MODEL_WEIGHTS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "weights",
    "pcb_board_det.pt",
)
PCB_BOARD_CONF_THRESHOLD = 0.5
PCB_BOARD_IOU_THRESHOLD = 0.45
PCB_BOARD_DETECT_COLOR = (0, 255, 0)
PCB_DEFECT_DETECT_COLOR = (0, 0, 255)
PCB_BOARD_PNP_TRIGGER_INTERVAL = 15

STEREO_PARAMS = {
    "BASELINE_CM": 3.00546,
    "FOV_HALF_DEG": 35.0,
    "DISP_IMAGE_WIDTH": 640,
    "FRAME_BUFFER_SIZE": 10,
}

STEREO_FOCAL_LENGTH_PX = 609.157

DISTANCE_VALID_MIN_CM = 45.0
DISTANCE_VALID_MAX_CM = 2000.0
DISTANCE_INVALID_LABEL = "distance invalid"
NO_DISPARITY_LABEL = "No disparity"

DEBUG_SGM_ENABLED = False
DEBUG_SGM_CENSUS_WIN = 5
DEBUG_SGM_MAX_DISPARITY = 48
DEBUG_SGM_P1 = 3
DEBUG_SGM_P2 = 24
DEBUG_SGM_CONFIDENCE_THRE = 1
DEBUG_SGM_SUBPIXEL_DIVISOR = 2.0
DEBUG_SGM_DIRECTIONS = 2
DEBUG_SGM_COST_TYPE = "hamming"
DEBUG_RECTIFICATION_LUT_DIR = None

PARALLEL_PIPELINE = {
    "MAX_WORKERS": 3,
    "BUFFER_MAX_AGE_SEC": 0.5,
    "BUFFER_MAX_SIZE": 20,
    "ENABLED": True,
}
