# ----------------------------------------
# Created on: Mon Sep 22 21:12:57 2025
# Auto generated by Pango
# Modified for Full System Simulation
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "/PDS_sim_library/usim"
vmap  adc "/PDS_sim_library/adc"
vmap  ddrc "/PDS_sim_library/ddrc"
vmap  ddrphy "/PDS_sim_library/ddrphy"
vmap  hsst_e2 "/PDS_sim_library/hsst_e2"
vmap  iolhr_dft "/PDS_sim_library/iolhr_dft"
vmap  ipal_e1 "/PDS_sim_library/ipal_e1"
vmap  pciegen2 "/PDS_sim_library/pciegen2"

# ============================================================
# All RTL and IP Core Files
# ============================================================
vlog  -sv -f define.f -work work   \
"".../ddr3_50h/ddr3_50h.v"\
".../ddr3_50h/ddr3_50h_ddrphy_top.v"\
".../ddr3_50h/rtl/ipsxb_rst_sync_v1_1.v"\
".../ddr3_50h/rtl/pll/ipsxb_ddrphy_pll_v1_0.v"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_calib_mux_v1_3.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_calib_top_v1_5.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_control_path_adj_v1_0.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_data_slice_v1_5.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_data_slice_dqs_gate_cal_v1_3.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_data_slice_wrlvl_v1_5.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_dfi_v1_4.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_dll_update_ctrl_v1_0.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_dqsi_rdel_cal_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_dqs_gate_coarse_cal_v1_3.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_dqs_rddata_align_v1_3.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_drift_ctrl_v1_5.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_gate_update_ctrl_v1_5.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_gatecal_v1_3.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_info_v1_0.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_init_v1_0.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_main_ctrl_v1_5.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_rdcal_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_reset_ctrl_v1_4.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_rst_debounce_v1_0.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_slice_rddata_align_v1_0.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_training_ctrl_v1_0.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_upcal_v1_5.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_wdata_path_adj_v1_0.vp"\
".../ddr3_50h/sim_lib/rtl/ddrphy/ipsxb_ddrphy_wrlvl_v1_0.vp"\
".../ddr3_50h/rtl/ddrphy/ipsxb_ddrphy_slice_top_v1_5.v"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_apb_cross_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_calib_delay_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_cfg_apb_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_bm_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_rowaddr_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_sm_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_top_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_back_ctrl_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_buf_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_out_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_top_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_dfi_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_lp_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_mrs_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_prefetch_fifo_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_rdatapath_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_reg_fifo2_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_ui_axi_v1_2a.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_wdatapath_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_wdp_align_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_wdp_dcp_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/ipsxb_mcdq_wrapper_v1_2b.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_com_timing_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_tfaw_timing_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_tfaw_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_act2wr_pass_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_act_pass_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_pre_pass_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_rd_pass_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_ref_pass_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_wr_pass_v1_2.vp"\
".../ddr3_50h/sim_lib/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_trc_timing_v1_2.vp"\
".../ddr3_50h/rtl/mcdq_ctrl/distributed_fifo/ipsxb_distributed_fifo_v1_0.v"\
".../ddr3_50h/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_fifo_ctr_v1_0.v"\
".../ddr3_50h/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_fifo_v1_0_distributed_fifo_v1_0.v"\
".../ddr3_50h/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_sdpram_v1_0_distributed_fifo_v1_0.v"\
".../ddr3_50h/example_design/bench/mem/ddr3.sv"\
".../Verification_model/tb_DUT.v"